language: go

go:
  - tip

install:
  - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.36.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.36.zip
  - export PATH=$PATH:$PWD/go_appengine/

script:
  - goapp test
