language: go
go:
- 1.6
before_install:
- openssl aes-256-cbc -K $encrypted_de7a60f8584a_key -iv $encrypted_de7a60f8584a_iv
  -in MeanTweets-649a4f6fdca0.json.enc -out MeanTweets-649a4f6fdca0.json -d
install:
- export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/MeanTweets-649a4f6fdca0.json
- export CLOUDSDK_CORE_DISABLE_PROMPTS=1
- export CLOUDSDK_CORE_PROJECT=meantweets-1381
- if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash;
  fi
- "/home/travis/google-cloud-sdk/bin/gcloud beta emulators datastore start --no-legacy
  &"
- go get -t ./...
- source build_ui.sh
script:
- go test -v ./...
