language: go

go:
  - 1.6

install:
  - go get -t ./...
  - mkdir sdk
  - curl -o sdk.zip "https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.36.zip"
  - unzip sdk.zip -d sdk
  - rm -r sdk/go_appengine/demos
  - export APPENGINE_DEV_APPSERVER=$(pwd)/sdk/go_appengine/dev_appserver.py

script:
  - go version
  - sdk/go_appengine/goapp test -v ./...
