language: go

go:
  - 1.6

install:
  # If the SDK is not already cached, download it and unpack it.
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
      curl https://sdk.cloud.google.com | bash;
    fi

  - source /home/travis/.bashrc

  # Start the datastore emulator.
  - gcloud beta emulators datastore start --no-legacy

  # Install deps.
  - go get -t ./...


script:
  - go test -v ./...
