runtime: go
vm: true
manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10

handlers:
- url: /crawl
  script: _go_app
  login: admin

- url: /.*
  script: IGNORED
  secure: always

- url: /.*
  script: _go_app
