runtime: go
vm: true
instance_class: B1
manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.18
  disk_size_gb: 10

handlers:
- url: /.*
  script: IGNORED
  secure: always

- url: /.*
  script: _go_app
